# Generated by Django 2.2.3 on 2020-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_auto_20191221_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
